### ISSUE TITLE
Syntax check failed: no filter named 'to_nice_json'

### ISSUE THREAD

**Issue by kjenney** [drm/jinja2-lint#1]
to_nice_json is an ansible filter. How do I let Jinja know about it or invalidate this false alert?

**Comment by drm** [comment]
Hi, I proposed a fix in branch `feature/custom-loader`. It provides an example of how you can reuse this linter as a module and add custom logic to the loader.

The example adds a noop-filter to the jinja2 Environment for all specified filters. This is a very rudimentary fix, but it might serve your purpose well. Just add all known filters to the 'filters' list.

HTH, let me know :)

**Comment by drm** [comment]
I released this as 2.0.0, since it's a breaking change (j2-lint.py was renamed to j2lint.py).

**Comment by mastermindg** [comment]
Thanks!
